apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sales-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: sales-catalog/api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: sales-catalog-config
                  key: AUTH_URL
            - name: CATALOG_URL
              valueFrom:
                configMapKeyRef:
                  name: sales-catalog-config
                  key: CATALOG_URL
            - name: ORDERS_URL
              valueFrom:
                configMapKeyRef:
                  name: sales-catalog-config
                  key: ORDERS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sales-catalog
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
