apiVersion: v1
kind: Secret
metadata:
  name: sales-catalog-secrets
  namespace: sales-catalog
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017
  JWT_SECRET: dev_sales_catalog_secret_change_me
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-catalog-config
  namespace: sales-catalog
data:
  AUTH_URL: http://auth-service:3001
  CATALOG_URL: http://catalog-service:3002
  ORDERS_URL: http://orders-service:3003
