apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-catalog-config
  namespace: sales-catalog
data:
  AUTH_URL: http://auth-service:3001
  CATALOG_URL: http://catalog-service:3002
  ORDERS_URL: http://orders-service:3003
